### ISSUE TITLE
PrettyPrintFormatter.Ecto.run/1 infinite recursion issue

### ISSUE THREAD

**Issue by hidnasio** [san650/pretty_print_formatter#19]
Hey, first of all thanks for this library.

There is an issue with `PrettyPrintFormatter.Ecto.run\1` function, with some queries it enters in an infinite loop causing beam process to use all available ram memory eventually.

I created a PR with a test that triggers the issue https://github.com/san650/pretty_print_formatter/pull/18 and also I've updated the line I think is responsible of the error.

I started to have this issue with release 0.1.6 and looks like this change is the one that introduced the error https://github.com/san650/pretty_print_formatter/commit/90ceeb1d6379546068d73a5fbe5aad07929ca045#diff-aaba82bc10734f1454875f165f32082cR124.

**Comment by san650** [comment]
Fixed by #18
